const SEARCH_TRAIN = 'SEARCH_TRAIN';
const ADD_TO_BOOKMARK = 'ADD_TO_BOOKMARK';
const BOOKMARK_SELECTED = 'BOOKMARK_SELECTED';
const ALL_TRAIN_SELECTED = 'ALL_TRAIN_SELECTED';

export default {
    SEARCH_TRAIN,
    ADD_TO_BOOKMARK,
    BOOKMARK_SELECTED,
    ALL_TRAIN_SELECTED
}